name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Install premake5
        uses: abel0b/setup-premake@v1
      - name: Init submodule
        uses: snickerbockers/submodules-init@v4
        # https://lukasjoswiak.com/github-actions-protobuf/
      - name: Cache protobuf library
        id: cache-protobuf
        uses: actions/cache@v1
        with:
          path: protobuf
          key: ${{ runner.os }}-protobuf
      - name: Build protobuf library
        if: steps.cache-protobuf.outputs.cache-hit != 'true'
        run: |
          git clone https://github.com/protocolbuffers/protobuf.git
          cd protobuf
          git submodule update --init --recursive
          ./autogen.sh
          ./autogen.sh
          ./configure
          make
          make check
      - name: Install protobuf library
        run: |
          cd protobuf
          sudo make install
          sudo ldconfig
      - name: Build
        run: |
          cd $GITHUB_WORKSPACE
          premake5 gmake
          cd proj
          export config=release_x86-64
          make clean
          make
