name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: abel0b/setup-premake@v1
      - uses: snickerbockers/submodules-init@v4
      - name: Install Protoc
        uses: arduino/setup-protoc@v1

      - name: Build
        run: |
          cd $GITHUB_WORKSPACE
          premake5 gmake
          cd proj
          export config=release_x86-64
          make clean
          make
